<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");?>

<?$APPLICATION->IncludeComponent(
    "bitrix:catalog.element",
    "bootstrap_v4_quick",
    Array(
        "ACTION_VARIABLE" => "action",
        "ADD_DETAIL_TO_SLIDER" => "N",
        "ADD_ELEMENT_CHAIN" => "N",
        "ADD_PICT_PROP" => "MORE_PHOTO",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "N",
        "ADD_TO_BASKET_ACTION" => array(0=>"ADD",),
        "ADD_TO_BASKET_ACTION_PRIMARY" => array(0=>"ADD",),
        "AJAX_MODE" => "Y",
        "BACKGROUND_IMAGE" => "-",
        "BASKET_URL" => "//taiyan.ru/personal/cart/",
        "BRAND_USE" => "N",
        "BROWSER_TITLE" => "-",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_SECTION_ID_VARIABLE" => "N",
        "COMPATIBLE_MODE" => "Y",
        "COMPONENT_TEMPLATE" => "bootstrap_v4",
        "CONVERT_CURRENCY" => "N",
        "DETAIL_PICTURE_MODE" => array(0=>"",1=>"",),
        "DETAIL_URL" => "",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISPLAY_COMPARE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PREVIEW_TEXT_MODE" => "H",
        "ELEMENT_CODE" => "",
        "ELEMENT_ID" => $_GET["ID"],
        "FILE_404" => "/404.php",
        "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
        "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
        "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
        "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
        "GIFTS_MESS_BTN_BUY" => "Выбрать",
        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
        "GIFTS_SHOW_IMAGE" => "Y",
        "GIFTS_SHOW_NAME" => "Y",
        "GIFTS_SHOW_OLD_PRICE" => "Y",
        "HIDE_NOT_AVAILABLE_OFFERS" => "N",
        "IBLOCK_ID" => "13",
        "IBLOCK_TYPE" => "1c_catalog",
        "IMAGE_RESOLUTION" => "16by9",
        "LABEL_PROP" => array(),
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "LINK_IBLOCK_ID" => "",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_PROPERTY_SID" => "",
        "MAIN_BLOCK_PROPERTY_CODE" => array(),
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_COMMENTS_TAB" => "Комментарии",
        "MESS_DESCRIPTION_TAB" => "Описание",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "MESS_PRICE_RANGES_TITLE" => "Цены",
        "MESS_PROPERTIES_TAB" => "Характеристики",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_LIMIT" => "0",
        "PARTIAL_PRODUCT_PROPERTIES" => "Y",
        "PRICE_CODE" => array(0=>"Розница МСК",),
        "PRICE_VAT_INCLUDE" => "N",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
        "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
        "PRODUCT_PROPERTIES" => array(),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_SUBSCRIPTION" => "Y",
        "PROPERTY_CODE" => array(0=>"CML2_ARTICLE",1=>"",),
        "SECTION_CODE" => "",
        "SECTION_ID" => $arElement["IBLOCK_SECTION_ID"],
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_URL" => "",
        "SEF_MODE" => "N",
        "SET_BROWSER_TITLE" => "N",
        "SET_CANONICAL_URL" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "Y",
        "SET_TITLE" => "N",
        "SET_VIEWED_IN_COMPONENT" => "N",
        "SHOW_404" => "Y",
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DEACTIVATED" => "N",
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_MAX_QUANTITY" => "N",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_SLIDER" => "Y",
        "SLIDER_INTERVAL" => "5000",
        "SLIDER_PROGRESS" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "TEMPLATE_THEME" => "",
        "USE_COMMENTS" => "N",
        "USE_ELEMENT_COUNTER" => "Y",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_GIFTS_DETAIL" => "N",
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "Y",
        "USE_RATIO_IN_RANGES" => "N",
        "USE_VOTE_RATING" => "N"
    )
);?>
